---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

suites:
  - name: PDH_S1
    driver: 
      vm_hostname: PDHS1.local.com
      network: 
      - ["private_network", {ip: "192.168.56.111"}]
      customize:
      memory: 2048
      cpus: 2
    run_list:
      - recipe[PHD::default]
    attributes:

  - name: PDH_S2
    driver: 
      vm_hostname: PDHS2.local.com
      network: 
      - ["private_network", {ip: "192.168.56.112"}]
      customize:
      memory: 2048
      cpus: 2
    run_list:
      - recipe[PHD::default]
    attributes: